export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ALL_RAW_PRODUCT_REQUEST = "ALL_RAW_PRODUCT_REQUEST";
export const ALL_RAW_PRODUCT_SUCCESS = "ALL_RAW_PRODUCT_SUCCESS";
export const ALL_RAW_PRODUCT_FAIL = "ALL_RAW_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const NEW_PRODUCT_BID_REQUEST = "NEW_PRODUCT_BID_REQUEST";
export const NEW_PRODUCT_BID_SUCCESS = "NEW_PRODUCT_BID_SUCCESS";
export const NEW_PRODUCT_BID_RESET = "NEW_PRODUCT_BID_RESET";
export const NEW_PRODUCT_BID_FAIL = "NEW_PRODUCT_BID_FAIL";

export const ACTIVATE_AUTO_BID_REQUEST = "ACTIVATE_AUTO_BID_REQUEST";
export const ACTIVATE_AUTO_BID_SUCCESS = "ACTIVATE_AUTO_BID_SUCCESS";
export const ACTIVATE_AUTO_BID_RESET = "ACTIVATE_AUTO_BID_RESET";
export const ACTIVATE_AUTO_BID_FAIL = "ACTIVATE_AUTO_BID_FAIL";

export const UPDATE_AUTO_BID_REQUEST = "UPDATE_AUTO_BID_REQUEST";
export const UPDATE_AUTO_BID_SUCCESS = "UPDATE_AUTO_BID_SUCCESS";
export const UPDATE_AUTO_BID_RESET = "UPDATE_AUTO_BID_RESET";
export const UPDATE_AUTO_BID_FAIL = "UPDATE_AUTO_BID_FAIL";

export const ALL_BID_REQUEST = "ALL_BID_REQUEST";
export const ALL_BID_SUCCESS = "ALL_BID_SUCCESS";
export const ALL_BID_FAIL = "ALL_BID_FAIL";

export const AUTO_BID_REQUEST = "AUTO_BID_REQUEST";
export const AUTO_BID_SUCCESS = "AUTO_BID_SUCCESS";
export const AUTO_BID_FAIL = "AUTO_BID_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
