export const LOGIN_REQUEST_SELLER = "LOGIN_REQUEST_SELLER";
export const LOGIN_SUCCESS_SELLER = "LOGIN_SUCCESS_SELLER";
export const LOGIN_FAIL_SELLER = "LOGIN_FAIL_SELLER";

export const REGISTER_USER_REQUEST_SELLER = "REGISTER_USER_REQUEST_SELLER";
export const REGISTER_USER_SUCCESS_SELLER = "REGISTER_USER_SUCCESS_SELLER";
export const REGISTER_USER_FAIL_SELLER = "REGISTER_USER_FAIL_SELLER";

export const LOAD_USER_REQUEST_SELLER = "LOAD_USER_REQUEST_SELLER";
export const LOAD_USER_SUCCESS_SELLER = "LOAD_USER_SUCCESS_SELLER";
export const LOAD_USER_FAIL_SELLER = "LOAD_USER_FAIL_SELLER";

export const LOGOUT_SUCCESS_SELLER = "LOGOUT_SUCCESS_SELLER";
export const LOGOUT_FAIL_SELLER = "LOGOUT_FAIL_SELLER";

export const UPDATE_PROFILE_REQUEST_SELLER = "UPDATE_PROFILE_REQUEST_SELLER";
export const UPDATE_PROFILE_SUCCESS_SELLER = "UPDATE_PROFILE_SUCCESS_SELLER";
export const UPDATE_PROFILE_RESET_SELLER = "UPDATE_PROFILE_RESET_SELLER";
export const UPDATE_PROFILE_FAIL_SELLER = "UPDATE_PROFILE_FAIL_SELLER";

export const UPDATE_PASSWORD_REQUEST_SELLER = "UPDATE_PASSWORD_REQUEST_SELLER";
export const UPDATE_PASSWORD_SUCCESS_SELLER = "UPDATE_PASSWORD_SUCCESS_SELLER";
export const UPDATE_PASSWORD_RESET_SELLER = "UPDATE_PASSWORD_RESET_SELLER";
export const UPDATE_PASSWORD_FAIL_SELLER = "UPDATE_PASSWORD_FAIL_SELLER";

export const FORGOT_PASSWORD_REQUEST_SELLER = "FORGOT_PASSWORD_REQUEST_SELLER";
export const FORGOT_PASSWORD_SUCCESS_SELLER = "FORGOT_PASSWORD_SUCCESS_SELLER";
export const FORGOT_PASSWORD_FAIL_SELLER = "FORGOT_PASSWORD_FAIL_SELLER";

export const RESET_PASSWORD_REQUEST_SELLER = "RESET_PASSWORD_REQUEST_SELLER";
export const RESET_PASSWORD_SUCCESS_SELLER = "RESET_PASSWORD_SUCCESS_SELLER";
export const RESET_PASSWORD_FAIL_SELLER = "RESET_PASSWORD_FAIL_SELLER";

export const ALL_USERS_REQUEST_SELLER = "ALL_USERS_REQUEST_SELLER";
export const ALL_USERS_SUCCESS_SELLER = "ALL_USERS_SUCCESS_SELLER";
export const ALL_USERS_FAIL_SELLER = "ALL_USERS_FAIL_SELLER";

export const USER_DETAILS_REQUEST_SELLER = "USER_DETAILS_REQUEST_SELLER";
export const USER_DETAILS_SUCCESS_SELLER = "USER_DETAILS_SUCCESS_SELLER";
export const USER_DETAILS_FAIL_SELLER = "USER_DETAILS_FAIL_SELLER";

export const UPDATE_USER_REQUEST_SELLER = "UPDATE_USER_REQUEST_SELLER";
export const UPDATE_USER_SUCCESS_SELLER = "UPDATE_USER_SUCCESS_SELLER";
export const UPDATE_USER_RESET_SELLER = "UPDATE_USER_RESET_SELLER";
export const UPDATE_USER_FAIL_SELLER = "UPDATE_USER_FAIL_SELLER";

export const DELETE_USER_REQUEST_SELLER = "DELETE_USER_REQUEST_SELLER";
export const DELETE_USER_SUCCESS_SELLER = "DELETE_USER_SUCCESS_SELLER";
export const DELETE_USER_FAIL_SELLER = "DELETE_USER_FAIL_SELLER";
export const DELETE_USER_RESET_SELLER = "DELETE_USER_RESET_SELLER";

export const CLEAR_ERRORS_SELLER = "CLEAR_ERRORS_SELLER";
